### PR TITLE
fix(requester-node-http): fix handling chunked responses (#1161)

### LINKED ISSUE #1161: bug: unicode characters in responses are sometimes corrupted v4 (node)
Response text that contains unicode characters is corrupted on large responses when using within node. This behaviour can reproduced in algoliasearch v4, version 3 works fine. 

I boiled the problem down to the `NodeHttpRequester` which simply adds buffer chunks to a string which leads to problems if the buffer only contains part of the unicode character. e.g.:

```
> a = Buffer.from("öäü")
<Buffer c3 b6 c3 a4 c3 bc>
> b = Buffer.from([0xc3, 0xb6, 0xc3])
<Buffer c3 b6 c3>
> c = Buffer.from([0xa4, 0xc3, 0xbc])
<Buffer a4 c3 bc>
> d = "" + b + c;  // <--- This is the current implementation in @algolia/node-http-requester
'ö��ü'
> Buffer.concat([b,c]);
<Buffer c3 b6 c3 a4 c3 bc>
> Buffer.concat([b,c]).toString()
'öäü'
```

I already created a fix and will make a pull request shortly.

### PR DESCRIPTION
**Pull request by vschoettke**
Fix #1161

### CODE REVIEW

File: packages/requester-node-http/src/createNodeHttpRequester.ts [hunk 1]
```diff
@@ -40,7 +42,7 @@ export function createNodeHttpRequester(): Requester & Destroyable {
 
             resolve({
               status: response.statusCode || 0,
-              content,
+              content: Buffer.concat(contentBuffers).toString(),
```
Comment (Haroenv) [inline packages/requester-node-http/src/createNodeHttpRequester.ts:45]: I checked, and this seems to be the same as we had in v3: https://github.com/algolia/algoliasearch-client-javascript/blob/v3.20.3/src/server/builds/node.js#L187

Comment (nunomaduro) [reply packages/requester-node-http/src/createNodeHttpRequester.ts:45]: Thanks for that info, just finishing up shouldStop issue, and I will jump into this.
